import { boolean, date, doublePrecision, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();


export const jurisdictions = pgTable('jurisdictions', { id: uuid('id').primaryKey().defaultRandom(), slug: text('slug').notNull().unique(), name: text('name').notNull(), countryCode: text('country_code').notNull(), createdAt: createdAt() });
export const legislativeSessions = pgTable('legislative_sessions', { id: uuid('id').primaryKey().defaultRandom(), jurisdictionId: uuid('jurisdiction_id').notNull().references(() => jurisdictions.id), slug: text('slug').notNull(), name: text('name').notNull(), startsOn: date('starts_on'), endsOn: date('ends_on'), isCurrent: boolean('is_current').notNull().default(false), createdAt: createdAt() }, (table) => [uniqueIndex('legislative_sessions_jurisdiction_slug_uq').on(table.jurisdictionId, table.slug)]);
export const chambers = pgTable('chambers', { id: uuid('id').primaryKey().defaultRandom(), jurisdictionId: uuid('jurisdiction_id').notNull().references(() => jurisdictions.id), slug: text('slug').notNull(), name: text('name').notNull(), kind: text('kind').notNull(), createdAt: createdAt() }, (table) => [uniqueIndex('chambers_jurisdiction_slug_uq').on(table.jurisdictionId, table.slug)]);
export const legislators = pgTable('legislators', { id: uuid('id').primaryKey().defaultRandom(), jurisdictionId: uuid('jurisdiction_id').notNull().references(() => jurisdictions.id), externalKey: text('external_key').notNull(), name: text('name').notNull(), normalizedName: text('normalized_name').notNull(), createdAt: createdAt() }, (table) => [uniqueIndex('legislators_jurisdiction_external_uq').on(table.jurisdictionId, table.externalKey)]);
export const memberships = pgTable('memberships', { id: uuid('id').primaryKey().defaultRandom(), sessionId: uuid('session_id').notNull().references(() => legislativeSessions.id), chamberId: uuid('chamber_id').notNull().references(() => chambers.id), legislatorId: uuid('legislator_id').notNull().references(() => legislators.id), district: text('district').notNull(), party: text('party').notNull(), title: text('title').notNull(), startsOn: date('starts_on'), endsOn: date('ends_on'), sourceUrl: text('source_url'), createdAt: createdAt() }, (table) => [uniqueIndex('memberships_session_chamber_legislator_uq').on(table.sessionId, table.chamberId, table.legislatorId), index('memberships_legislator_idx').on(table.legislatorId), index('memberships_session_chamber_idx').on(table.sessionId, table.chamberId)]);

export const membershipSourceAliases = pgTable('membership_source_aliases', {
  id: uuid('id').primaryKey().defaultRandom(),
  membershipId: uuid('membership_id').notNull().references(() => memberships.id, { onDelete: 'cascade' }),
  sourceSystem: text('source_system').notNull(), sourceName: text('source_name').notNull(), normalizedName: text('normalized_name').notNull(), sourceUrl: text('source_url'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt(),
}, (table) => [uniqueIndex('membership_source_aliases_membership_source_name_uq').on(table.membershipId, table.sourceSystem, table.normalizedName), index('membership_source_aliases_lookup_idx').on(table.sourceSystem, table.normalizedName, table.membershipId)]);

export const bills = pgTable('bills', { id: uuid('id').primaryKey().defaultRandom(), sessionId: uuid('session_id').notNull().references(() => legislativeSessions.id), originatingChamberId: uuid('originating_chamber_id').references(() => chambers.id), identifier: text('identifier').notNull(), title: text('title').notNull(), status: text('status'), sourceUrl: text('source_url'), introducedAt: timestamp('introduced_at', { withTimezone: true }), latestActionAt: timestamp('latest_action_at', { withTimezone: true }), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [uniqueIndex('bills_session_identifier_uq').on(table.sessionId, table.identifier), index('bills_session_idx').on(table.sessionId)]);
export const billVersions = pgTable('bill_versions', { id: uuid('id').primaryKey().defaultRandom(), billId: uuid('bill_id').notNull().references(() => bills.id), versionKey: text('version_key').notNull(), publishedAt: timestamp('published_at', { withTimezone: true }), textUrl: text('text_url'), textHash: text('text_hash'), rawText: text('raw_text'), sourceUrl: text('source_url'), createdAt: createdAt() }, (table) => [uniqueIndex('bill_versions_bill_key_uq').on(table.billId, table.versionKey), index('bill_versions_bill_published_idx').on(table.billId, table.publishedAt)]);
export const billFeatureSets = pgTable('bill_feature_sets', { id: uuid('id').primaryKey().defaultRandom(), billVersionId: uuid('bill_version_id').notNull().references(() => billVersions.id, { onDelete: 'cascade' }), featureSchemaVersion: text('feature_schema_version').notNull(), extractorKind: text('extractor_kind').notNull(), extractorVersion: text('extractor_version').notNull(), features: jsonb('features').notNull(), confidence: jsonb('confidence').notNull().default({}), provenance: jsonb('provenance').notNull().default({}), generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(), createdAt: createdAt() }, (table) => [uniqueIndex('bill_feature_sets_version_extractor_uq').on(table.billVersionId, table.featureSchemaVersion, table.extractorKind, table.extractorVersion), index('bill_feature_sets_version_idx').on(table.billVersionId, table.generatedAt), index('bill_feature_sets_schema_idx').on(table.featureSchemaVersion, table.extractorKind, table.extractorVersion)]);

export const proposals = pgTable('proposals', { id: uuid('id').primaryKey().defaultRandom(), ownerUserId: text('owner_user_id').notNull(), title: text('title').notNull(), description: text('description'), rawText: text('raw_text'), targetChamberId: uuid('target_chamber_id').references(() => chambers.id), createdAt: createdAt(), updatedAt: updatedAt() });
export const forecasts = pgTable('forecasts', { id: uuid('id').primaryKey().defaultRandom(), ownerUserId: text('owner_user_id').notNull(), targetType: text('target_type').notNull(), targetKind: text('target_kind').notNull(), conditionalOn: text('conditional_on'), billId: uuid('bill_id').references(() => bills.id), proposalId: uuid('proposal_id').references(() => proposals.id), targetChamberId: uuid('target_chamber_id').notNull().references(() => chambers.id), sessionId: uuid('session_id').references(() => legislativeSessions.id), status: text('status').notNull().default('draft'), archivedAt: timestamp('archived_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [index('forecasts_owner_updated_idx').on(table.ownerUserId, table.updatedAt), index('forecasts_session_idx').on(table.sessionId, table.updatedAt)]);
export const forecastRevisions = pgTable('forecast_revisions', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id), revisionNumber: integer('revision_number').notNull(), researchMode: text('research_mode').notNull(), billVersionId: uuid('bill_version_id').references(() => billVersions.id), generatedAt: timestamp('generated_at', { withTimezone: true }), passageProbability: doublePrecision('passage_probability'), expectedYes: doublePrecision('expected_yes'), yesLow: doublePrecision('yes_low'), yesHigh: doublePrecision('yes_high'), modelVersion: text('model_version'), calibrationStatus: text('calibration_status').notNull().default('unvalidated'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_revisions_forecast_number_uq').on(table.forecastId, table.revisionNumber), index('forecast_revisions_forecast_created_idx').on(table.forecastId, table.createdAt)]);
export const forecastMemberPredictions = pgTable('forecast_member_predictions', { id: uuid('id').primaryKey().defaultRandom(), revisionId: uuid('revision_id').notNull().references(() => forecastRevisions.id), membershipId: uuid('membership_id').notNull().references(() => memberships.id), yesProbability: doublePrecision('yes_probability'), probabilityLow: doublePrecision('probability_low'), probabilityHigh: doublePrecision('probability_high'), evidenceQuality: text('evidence_quality').notNull(), cannotPredictReason: text('cannot_predict_reason'), reasoningSummary: text('reasoning_summary'), facts: jsonb('facts').notNull().default([]), inferences: jsonb('inferences').notNull().default([]), context: jsonb('context').notNull().default([]), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_member_predictions_revision_membership_uq').on(table.revisionId, table.membershipId), index('forecast_member_predictions_revision_idx').on(table.revisionId)]);

export const sourceDocuments = pgTable('source_documents', { id: uuid('id').primaryKey().defaultRandom(), jurisdictionId: uuid('jurisdiction_id').notNull().references(() => jurisdictions.id), sessionId: uuid('session_id').references(() => legislativeSessions.id), chamberId: uuid('chamber_id').references(() => chambers.id), sourceKind: text('source_kind').notNull(), sourceUrl: text('source_url').notNull(), fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(), contentSha256: text('content_sha256').notNull(), httpStatus: integer('http_status'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('source_documents_url_hash_uq').on(table.sourceUrl, table.contentSha256), index('source_documents_session_chamber_idx').on(table.sessionId, table.chamberId, table.fetchedAt)]);
export const ingestionRuns = pgTable('ingestion_runs', { id: uuid('id').primaryKey().defaultRandom(), sourceSystem: text('source_system').notNull(), scope: text('scope').notNull(), status: text('status').notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp('finished_at', { withTimezone: true }), sourceDocuments: integer('source_documents').notNull().default(0), voteEvents: integer('vote_events').notNull().default(0), memberVotes: integer('member_votes').notNull().default(0), unresolvedMembers: integer('unresolved_members').notNull().default(0), errorSummary: text('error_summary'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() });
export const voteEvents = pgTable('vote_events', { id: uuid('id').primaryKey().defaultRandom(), sessionId: uuid('session_id').notNull().references(() => legislativeSessions.id), chamberId: uuid('chamber_id').notNull().references(() => chambers.id), billId: uuid('bill_id').references(() => bills.id), sourceDocumentId: uuid('source_document_id').notNull().references(() => sourceDocuments.id), externalKey: text('external_key').notNull(), voteKind: text('vote_kind').notNull(), motionText: text('motion_text').notNull(), amendmentRef: text('amendment_ref'), occurredOn: date('occurred_on').notNull(), journalPage: text('journal_page'), yeaCount: integer('yea_count').notNull(), nayCount: integer('nay_count').notNull(), otherCount: integer('other_count').notNull().default(0), passed: boolean('passed'), isPassage: boolean('is_passage').notNull().default(false), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('vote_events_session_chamber_external_uq').on(table.sessionId, table.chamberId, table.externalKey), index('vote_events_session_chamber_date_idx').on(table.sessionId, table.chamberId, table.occurredOn), index('vote_events_bill_idx').on(table.billId, table.occurredOn), index('vote_events_passage_idx').on(table.sessionId, table.chamberId, table.isPassage, table.occurredOn)]);
export const memberVotes = pgTable('member_votes', { id: uuid('id').primaryKey().defaultRandom(), voteEventId: uuid('vote_event_id').notNull().references(() => voteEvents.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').references(() => memberships.id), sourceMemberName: text('source_member_name').notNull(), normalizedMemberName: text('normalized_member_name').notNull(), choice: text('choice').notNull(), sourceOrdinal: integer('source_ordinal'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('member_votes_event_name_uq').on(table.voteEventId, table.normalizedMemberName), index('member_votes_membership_idx').on(table.membershipId, table.voteEventId)]);
export const legislativeStageEvents = pgTable('legislative_stage_events', { id: uuid('id').primaryKey().defaultRandom(), billId: uuid('bill_id').notNull().references(() => bills.id, { onDelete: 'cascade' }), sessionId: uuid('session_id').notNull().references(() => legislativeSessions.id), chamberId: uuid('chamber_id').references(() => chambers.id), stageKind: text('stage_kind').notNull(), outcome: boolean('outcome'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), sourceUrl: text('source_url').notNull(), sourceDocumentId: uuid('source_document_id').references(() => sourceDocuments.id), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('legislative_stage_events_bill_kind_time_url_uq').on(table.billId, table.stageKind, table.occurredAt, table.sourceUrl), index('legislative_stage_events_bill_time_idx').on(table.billId, table.occurredAt), index('legislative_stage_events_session_stage_idx').on(table.sessionId, table.stageKind, table.occurredAt)]);
export const voteRules = pgTable('vote_rules', { id: uuid('id').primaryKey().defaultRandom(), jurisdictionId: uuid('jurisdiction_id').notNull().references(() => jurisdictions.id), chamberId: uuid('chamber_id').references(() => chambers.id), motionKind: text('motion_kind').notNull(), thresholdKind: text('threshold_kind').notNull(), numerator: integer('numerator'), denominator: integer('denominator'), fixedRequiredYes: integer('fixed_required_yes'), effectiveFrom: date('effective_from'), effectiveTo: date('effective_to'), sourceUrl: text('source_url').notNull(), notes: text('notes'), createdAt: createdAt() });

export const evidenceItems = pgTable('evidence_items', { id: uuid('id').primaryKey().defaultRandom(), sourceDocumentId: uuid('source_document_id').notNull().references(() => sourceDocuments.id, { onDelete: 'cascade' }), billId: uuid('bill_id').references(() => bills.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').references(() => memberships.id, { onDelete: 'cascade' }), evidenceKind: text('evidence_kind').notNull(), stance: text('stance'), claim: text('claim').notNull(), excerpt: text('excerpt'), publishedAt: timestamp('published_at', { withTimezone: true }), sourceQuality: text('source_quality').notNull(), relevance: text('relevance').notNull(), freshness: text('freshness').notNull(), extractionMethod: text('extraction_method').notNull(), extractionVersion: text('extraction_version'), confidence: doublePrecision('confidence'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [index('evidence_items_source_idx').on(table.sourceDocumentId, table.createdAt), index('evidence_items_bill_idx').on(table.billId, table.createdAt), index('evidence_items_membership_idx').on(table.membershipId, table.createdAt)]);
export const evidenceRelationships = pgTable('evidence_relationships', { id: uuid('id').primaryKey().defaultRandom(), fromEvidenceId: uuid('from_evidence_id').notNull().references(() => evidenceItems.id, { onDelete: 'cascade' }), toEvidenceId: uuid('to_evidence_id').notNull().references(() => evidenceItems.id, { onDelete: 'cascade' }), relationKind: text('relation_kind').notNull(), reason: text('reason'), createdAt: createdAt() }, (table) => [uniqueIndex('evidence_relationships_unique_uq').on(table.fromEvidenceId, table.toEvidenceId, table.relationKind)]);
export const researchRuns = pgTable('research_runs', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), baseRevisionId: uuid('base_revision_id').references(() => forecastRevisions.id, { onDelete: 'set null' }), resultRevisionId: uuid('result_revision_id').references(() => forecastRevisions.id, { onDelete: 'set null' }), provider: text('provider').notNull(), providerVersion: text('provider_version'), status: text('status').notNull(), asOf: timestamp('as_of', { withTimezone: true }).notNull(), targetLimit: integer('target_limit').notNull(), configuration: jsonb('configuration').notNull().default({}), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp('finished_at', { withTimezone: true }), errorSummary: text('error_summary'), createdAt: createdAt() }, (table) => [index('research_runs_forecast_idx').on(table.forecastId, table.createdAt)]);
export const researchRunTargets = pgTable('research_run_targets', { id: uuid('id').primaryKey().defaultRandom(), researchRunId: uuid('research_run_id').notNull().references(() => researchRuns.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').notNull().references(() => memberships.id, { onDelete: 'cascade' }), targetRank: integer('target_rank').notNull(), pivotality: doublePrecision('pivotality').notNull(), uncertainty: doublePrecision('uncertainty').notNull(), evidenceGap: doublePrecision('evidence_gap').notNull(), priorityScore: doublePrecision('priority_score').notNull(), rationale: text('rationale').notNull(), createdAt: createdAt() }, (table) => [uniqueIndex('research_run_targets_member_uq').on(table.researchRunId, table.membershipId), uniqueIndex('research_run_targets_rank_uq').on(table.researchRunId, table.targetRank)]);
export const forecastRevisionEvidence = pgTable('forecast_revision_evidence', { id: uuid('id').primaryKey().defaultRandom(), revisionId: uuid('revision_id').notNull().references(() => forecastRevisions.id, { onDelete: 'cascade' }), evidenceItemId: uuid('evidence_item_id').notNull().references(() => evidenceItems.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').references(() => memberships.id, { onDelete: 'set null' }), disposition: text('disposition').notNull(), rationale: text('rationale').notNull(), probabilityBefore: doublePrecision('probability_before'), probabilityAfter: doublePrecision('probability_after'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_revision_evidence_uq').on(table.revisionId, table.evidenceItemId, table.membershipId), index('forecast_revision_evidence_revision_idx').on(table.revisionId, table.createdAt)]);

export const forecastScenarios = pgTable('forecast_scenarios', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), baseRevisionId: uuid('base_revision_id').notNull().references(() => forecastRevisions.id, { onDelete: 'cascade' }), ownerUserId: text('owner_user_id').notNull(), name: text('name').notNull(), notes: text('notes'), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [index('forecast_scenarios_forecast_idx').on(table.forecastId, table.createdAt), index('forecast_scenarios_base_revision_idx').on(table.baseRevisionId, table.createdAt)]);
export const scenarioOverrides = pgTable('scenario_overrides', { id: uuid('id').primaryKey().defaultRandom(), scenarioId: uuid('scenario_id').notNull().references(() => forecastScenarios.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').notNull().references(() => memberships.id, { onDelete: 'cascade' }), yesProbability: doublePrecision('yes_probability').notNull(), rationale: text('rationale'), createdAt: createdAt() }, (table) => [uniqueIndex('scenario_overrides_scenario_member_uq').on(table.scenarioId, table.membershipId)]);
export const forecastSubsets = pgTable('forecast_subsets', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), ownerUserId: text('owner_user_id').notNull(), name: text('name').notNull(), sourceKind: text('source_kind').notNull().default('custom'), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [index('forecast_subsets_forecast_idx').on(table.forecastId, table.createdAt)]);
export const forecastSubsetMembers = pgTable('forecast_subset_members', { id: uuid('id').primaryKey().defaultRandom(), subsetId: uuid('subset_id').notNull().references(() => forecastSubsets.id, { onDelete: 'cascade' }), membershipId: uuid('membership_id').notNull().references(() => memberships.id, { onDelete: 'cascade' }), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_subset_members_subset_member_uq').on(table.subsetId, table.membershipId), index('forecast_subset_members_membership_idx').on(table.membershipId, table.subsetId)]);
export const forecastShareLinks = pgTable('forecast_share_links', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), revisionId: uuid('revision_id').notNull().references(() => forecastRevisions.id, { onDelete: 'cascade' }), ownerUserId: text('owner_user_id').notNull(), tokenHash: text('token_hash').notNull(), label: text('label'), revokedAt: timestamp('revoked_at', { withTimezone: true }), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_share_links_token_hash_uq').on(table.tokenHash), index('forecast_share_links_forecast_idx').on(table.forecastId, table.createdAt), index('forecast_share_links_revision_idx').on(table.revisionId, table.createdAt)]);

export const forecastResolutions = pgTable('forecast_resolutions', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), voteEventId: uuid('vote_event_id').notNull().references(() => voteEvents.id, { onDelete: 'restrict' }), resolutionKind: text('resolution_kind').notNull().default('official_passage'), resolvedAt: timestamp('resolved_at', { withTimezone: true }).notNull().defaultNow(), metadata: jsonb('metadata').notNull().default({}), createdAt: createdAt() }, (table) => [uniqueIndex('forecast_resolutions_forecast_uq').on(table.forecastId), index('forecast_resolutions_vote_event_idx').on(table.voteEventId, table.resolvedAt)]);
export const externalUsageEvents = pgTable('external_usage_events', { id: uuid('id').primaryKey().defaultRandom(), provider: text('provider').notNull(), operation: text('operation').notNull(), forecastId: uuid('forecast_id').references(() => forecasts.id, { onDelete: 'set null' }), researchRunId: uuid('research_run_id').references(() => researchRuns.id, { onDelete: 'set null' }), success: boolean('success').notNull(), units: jsonb('units').notNull().default({}), errorSummary: text('error_summary'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(), metadata: jsonb('metadata').notNull().default({}) }, (table) => [index('external_usage_events_provider_idx').on(table.provider, table.operation, table.occurredAt), index('external_usage_events_forecast_idx').on(table.forecastId, table.occurredAt), index('external_usage_events_research_run_idx').on(table.researchRunId, table.occurredAt)]);
export const forecastSchedules = pgTable('forecast_schedules', { forecastId: uuid('forecast_id').primaryKey().references(() => forecasts.id, { onDelete: 'cascade' }), enabled: boolean('enabled').notNull().default(true), cadenceHours: integer('cadence_hours').notNull().default(24), researchMode: text('research_mode').notNull().default('quick'), nextRunAt: timestamp('next_run_at', { withTimezone: true }).notNull().defaultNow(), lastRunAt: timestamp('last_run_at', { withTimezone: true }), consecutiveFailures: integer('consecutive_failures').notNull().default(0), createdAt: createdAt(), updatedAt: updatedAt() }, (table) => [index('forecast_schedules_due_idx').on(table.nextRunAt)]);
export const forecastSnapshotRuns = pgTable('forecast_snapshot_runs', { id: uuid('id').primaryKey().defaultRandom(), forecastId: uuid('forecast_id').notNull().references(() => forecasts.id, { onDelete: 'cascade' }), scheduledFor: timestamp('scheduled_for', { withTimezone: true }).notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp('finished_at', { withTimezone: true }), status: text('status').notNull(), revisionId: uuid('revision_id').references(() => forecastRevisions.id, { onDelete: 'set null' }), resolutionId: uuid('resolution_id').references(() => forecastResolutions.id, { onDelete: 'set null' }), errorSummary: text('error_summary'), metadata: jsonb('metadata').notNull().default({}) }, (table) => [uniqueIndex('forecast_snapshot_runs_forecast_scheduled_uq').on(table.forecastId, table.scheduledFor), index('forecast_snapshot_runs_forecast_idx').on(table.forecastId, table.startedAt)]);
export const modelDriftAlerts = pgTable('model_drift_alerts', { id: uuid('id').primaryKey().defaultRandom(), modelVersion: text('model_version').notNull(), sliceKey: text('slice_key').notNull(), metric: text('metric').notNull(), baselineValue: doublePrecision('baseline_value').notNull(), observedValue: doublePrecision('observed_value').notNull(), threshold: doublePrecision('threshold').notNull(), sampleSize: integer('sample_size').notNull(), status: text('status').notNull().default('open'), detectedAt: timestamp('detected_at', { withTimezone: true }).notNull().defaultNow(), resolvedAt: timestamp('resolved_at', { withTimezone: true }), metadata: jsonb('metadata').notNull().default({}) }, (table) => [index('model_drift_alerts_status_idx').on(table.status, table.detectedAt)]);
