import test from 'node:test';
import assert from 'node:assert/strict';
import { calibrateProbability, estimateMemberProbability, fitProbabilityCalibrator } from '../src/forecasting/member-model.js';
import { empiricalIntervalCoverage, poissonBinomialDistribution, requiredYesForRule, simulateChamber } from '../src/forecasting/chamber.js';

test('member model shrinks member history through party and global evidence', () => { const result = estimateMemberProbability({ memberId: 'm1', party: 'DFL', global: { yes: 80, total: 100 }, partyHistory: { yes: 18, total: 20 }, memberHistory: { yes: 1, total: 2 } }); assert.ok(result.probability !== undefined); assert.ok(result.probability! > 0.5); assert.ok(result.probability! < 0.9); });
test('analogue evidence nudges rather than overwhelms member history', () => { const base = estimateMemberProbability({ memberId: 'm1', party: 'R', global: { yes: 70, total: 100 }, partyHistory: { yes: 3, total: 20 }, memberHistory: { yes: 1, total: 10 } }); const withAnalogue = estimateMemberProbability({ memberId: 'm1', party: 'R', global: { yes: 70, total: 100 }, partyHistory: { yes: 3, total: 20 }, memberHistory: { yes: 1, total: 10 }, analogueYesRate: 0.8, analogueEffectiveWeight: 4 }); assert.ok(withAnalogue.probability! > base.probability!); assert.ok(withAnalogue.probability! < 0.8); });
test('low-information cases can explicitly refuse false precision', () => { const result = estimateMemberProbability({ memberId: 'new', party: 'I', global: { yes: 2, total: 4 } }); assert.equal(result.probability, undefined); assert.match(result.cannotPredictReason ?? '', /insufficient/); });
test('calibrator uses historical bins and leaves unsupported bins unchanged', () => { const observations = Array.from({ length: 50 }, (_, index) => ({ probability: index < 25 ? 0.2 : 0.8, outcome: (index < 25 ? 0 : 1) as 0 | 1 })); const calibrator = fitProbabilityCalibrator(observations, { bins: 5, minimumBinSize: 10, smoothing: 0 }); assert.equal(calibrateProbability(0.2, calibrator), 0.005); assert.equal(calibrateProbability(0.8, calibrator), 0.995); assert.equal(calibrateProbability(0.5, calibrator), 0.5); });
test('poisson-binomial chamber simulation is exact for two fair members', () => { const distribution = poissonBinomialDistribution([0.5, 0.5]); assert.deepEqual(distribution.map((value) => Number(value.toFixed(6))), [0.25, 0.5, 0.25]); const simulation = simulateChamber([0.5, 0.5], { kind: 'fixed', requiredYes: 2 }); assert.equal(Number(simulation.passageProbability.toFixed(6)), 0.25); assert.equal(simulation.expectedYes, 1); });
test('chamber passage probability remains within the unit interval after floating-point accumulation', () => { const simulation = simulateChamber(Array(133).fill(0.97), { kind: 'fixed', requiredYes: 67 }); assert.equal(simulation.passageProbability, 1); });
test('procedure rules represent simple and supermajority thresholds explicitly', () => { assert.equal(requiredYesForRule({ kind: 'majority-of-cast' }, 133), 67); assert.equal(requiredYesForRule({ kind: 'absolute-majority', seats: 134 }), 68); assert.equal(requiredYesForRule({ kind: 'fraction-of-seats', seats: 67, numerator: 2, denominator: 3 }), 45); });
test('empirical interval coverage is measurable', () => { assert.equal(empiricalIntervalCoverage([{ actualYes: 60, yesLow: 55, yesHigh: 65 }, { actualYes: 70, yesLow: 55, yesHigh: 65 }]), 0.5); });
