import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const EXPECTED_ROWS=135457;
const EXPECTED_ROW_KEYS='3aa47101f9e4a848e293fdaa89ef853919d49826b68ae90960370c5c19e9df72';
const OUTPUT='evidence-quality-historical-feature-coverage-v1.7.json';
type MatrixRow={schemaVersion:string;voteEventId:string;membershipId:string;legislatorId:string;session:string;chamber:string;occurredOn:string;billId:string;identifier:string;eventStatus:string;features:number[];reviewedApplicabilityFeatures:number[];reviewedApplicability:null|Record<string,unknown>};
type Manifest={schemaVersion:string;issue:number;targetUniverse:{rows:number;rowKeySha256:string};featureFamilies:{exactBill:{nonzeroRows:number};reviewedApplicability:{nonzeroRows:number;previousNonzeroRows:number;netAddedRows:number}};coverage:{matrixRows:number;exactNonzeroRows:number;reviewedApplicabilityNonzeroRows:number;combinedNonzeroRows:number;overlapRows:number;membershipsWithCombinedDirectionalEvidence:number;eventsWithCombinedDirectionalEvidence:number;netAddedCombinedRowsVsV16:number;exactRowsChangedVsV16:number;reviewedApplicabilityRowsChangedOutsideAdditions:number;bySession:Record<string,{rows:number;exactNonzeroRows:number;reviewedApplicabilityNonzeroRows:number;combinedNonzeroRows:number}>};applicabilityGate:{candidateReviewGroups:number;candidateClaimPairs:number;decisionCounts:Record<string,{groups:number;pairs:number}>;finalPairStatusCounts:Record<string,number>;applicableRows:number};digests:{matrixCanonicalNdjsonSha256:string;matrixGzipSha256:string};policy:Record<string,unknown>};
function env(name:string):string{const v=process.env[name]?.trim();if(!v)throw new Error(`${name} is required`);return v;}
function sha(v:string|Buffer):string{return createHash('sha256').update(v).digest('hex');}
function nonzero(v:readonly number[]):boolean{return v.some((x)=>x!==0);}
function main():void{
 const manifest=JSON.parse(readFileSync(env('VOTEPREDICT_EQ_V17_MANIFEST_PATH'),'utf8')) as Manifest; const gz=readFileSync(env('VOTEPREDICT_EQ_V17_MATRIX_PATH')); const outDir=env('VOTEPREDICT_EQ_V17_COVERAGE_OUTPUT_DIR');
 if(manifest.schemaVersion!=='evidence-quality-historical-feature-matrix-v1.7-manifest'||manifest.issue!==718||manifest.targetUniverse.rows!==EXPECTED_ROWS||manifest.targetUniverse.rowKeySha256!==EXPECTED_ROW_KEYS||manifest.featureFamilies.exactBill.nonzeroRows!==38||manifest.featureFamilies.reviewedApplicability.nonzeroRows!==6||manifest.featureFamilies.reviewedApplicability.previousNonzeroRows!==2||manifest.featureFamilies.reviewedApplicability.netAddedRows!==4||manifest.coverage.exactNonzeroRows!==38||manifest.coverage.reviewedApplicabilityNonzeroRows!==6||manifest.coverage.combinedNonzeroRows!==44||manifest.coverage.overlapRows!==0||manifest.coverage.netAddedCombinedRowsVsV16!==4||manifest.coverage.exactRowsChangedVsV16!==0||manifest.coverage.reviewedApplicabilityRowsChangedOutsideAdditions!==0||manifest.applicabilityGate.candidateReviewGroups!==124||manifest.applicabilityGate.candidateClaimPairs!==138||manifest.applicabilityGate.decisionCounts.applicable?.groups!==4||manifest.applicabilityGate.decisionCounts.ambiguous_fail_closed?.groups!==17||manifest.applicabilityGate.decisionCounts.not_applicable?.groups!==103||manifest.applicabilityGate.decisionCounts.pending_review?.groups!==0||manifest.applicabilityGate.finalPairStatusCounts.ambiguous_fail_closed!==91||manifest.applicabilityGate.finalPairStatusCounts.pending_review!==0||manifest.applicabilityGate.applicableRows!==4||manifest.policy.outcomeUseDuringFeatureConstruction!=='none'||manifest.policy.pendingOrAmbiguousApplicabilityIncluded!==false||manifest.policy.productionDatabaseQueried!==false||manifest.policy.productionWrites!==false||manifest.policy.vercelUsed!==false||manifest.policy.modelFitting!=='none'||manifest.policy.servingChanged!==false)throw new Error('v1.7 manifest identity/policy drifted');
 if(sha(gz)!==manifest.digests.matrixGzipSha256)throw new Error('v1.7 gzip digest mismatch'); const canonical=gunzipSync(gz).toString('utf8'); if(sha(canonical)!==manifest.digests.matrixCanonicalNdjsonSha256)throw new Error('v1.7 canonical digest mismatch');
 const rows=canonical.trimEnd().split('\n').map((line)=>JSON.parse(line) as MatrixRow); if(rows.length!==EXPECTED_ROWS)throw new Error(`Expected ${EXPECTED_ROWS}, got ${rows.length}`); const keys=rows.map((r)=>`${r.voteEventId}|${r.membershipId}`).sort(); if(sha(keys.join('\n')+'\n')!==EXPECTED_ROW_KEYS)throw new Error('row-key digest drifted');
 const expectedKeys=['billId','chamber','eventStatus','features','identifier','legislatorId','membershipId','occurredOn','reviewedApplicability','reviewedApplicabilityFeatures','schemaVersion','session','voteEventId'].sort().join('|'); let exact=0,app=0,combined=0,overlap=0;const memberships=new Set<string>(),events=new Set<string>();const sessions:Record<string,{rows:number;exactNonzeroRows:number;reviewedApplicabilityNonzeroRows:number;combinedNonzeroRows:number}>={};
 for(const row of rows){if(Object.keys(row).sort().join('|')!==expectedKeys)throw new Error(`row schema drifted ${row.voteEventId}|${row.membershipId}`);if(row.schemaVersion!=='evidence-quality-historical-feature-matrix-v1.7'||row.features.length!==12||row.reviewedApplicabilityFeatures.length!==12)throw new Error(`row feature schema drifted ${row.voteEventId}|${row.membershipId}`);const e=nonzero(row.features),a=nonzero(row.reviewedApplicabilityFeatures);if(e)exact++;if(a)app++;if(e||a){combined++;memberships.add(row.membershipId);events.add(row.voteEventId);}if(e&&a)overlap++;const s=sessions[row.session]??={rows:0,exactNonzeroRows:0,reviewedApplicabilityNonzeroRows:0,combinedNonzeroRows:0};s.rows++;if(e)s.exactNonzeroRows++;if(a)s.reviewedApplicabilityNonzeroRows++;if(e||a)s.combinedNonzeroRows++;}
 const s21=sessions['2021-2022'],s23=sessions['2023-2024'],s25=sessions['2025-2026'];if(exact!==38||app!==6||combined!==44||overlap!==0||memberships.size!==30||events.size!==39||!s21||s21.rows!==35510||s21.exactNonzeroRows!==3||s21.reviewedApplicabilityNonzeroRows!==6||s21.combinedNonzeroRows!==9||!s23||s23.combinedNonzeroRows!==32||!s25||s25.combinedNonzeroRows!==3)throw new Error(`coverage recomputation drifted: ${JSON.stringify({exact,app,combined,overlap,memberships:memberships.size,events:events.size,sessions})}`);
 const report={schemaVersion:'evidence-quality-historical-feature-coverage-v1.7',generatedAt:new Date().toISOString(),issue:718,summary:{targetRows:rows.length,exactNonzeroRows:exact,reviewedApplicabilityNonzeroRows:app,combinedNonzeroRows:combined,netAddedRowsVsV16:4,exactRowsChangedVsV16:0,exactRowsRemovedVsV16:0,overlapRows:overlap,membershipsWithCombinedDirectionalEvidence:memberships.size,eventsWithCombinedDirectionalEvidence:events.size},bySession:sessions,training:{session:'2021-2022',targetRows:s21.rows,coveredRows:s21.combinedNonzeroRows,coverageRate:s21.combinedNonzeroRows/s21.rows},review:{candidateReviewGroups:124,candidateClaimPairs:138,applicableGroups:4,ambiguousFailClosedPairs:91,pendingPairs:0,ambiguousOrPendingRowsIncludedInMatrix:0},interpretation:{modelingReady:false,reason:'Nine strict directional 2021-22 rows remain too sparse for responsible model fitting; continue evidence-density work.'},policy:{outcomeUse:'none',productionDatabaseQueried:false,productionWrites:false,vercelUsed:false,exactBillEvidenceChanged:false,previousReviewedApplicabilityChanged:false,pendingOrAmbiguousApplicabilityIncluded:false,modelFitting:'none',servingChanged:false}};
 mkdirSync(outDir,{recursive:true});writeFileSync(resolve(outDir,OUTPUT),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({historicalCoverageV17:report.summary,training:report.training,modelingReady:false},null,2));
}
main();
