import type { P2ApplicabilityClaimRule } from './historical-density-p2-applicability.js';

export const P2_REMAINING_APPLICABILITY_RULES: readonly P2ApplicabilityClaimRule[] = [
  {
    id: 'coleman_pro_life',
    sourceRows: [1, 6, 36],
    memberName: 'Julia E. Coleman',
    stance: 'supports',
    normalizedClaim: 'Julia Coleman supports protecting unborn life.',
    issueFamily: 'abortion',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'abortion', source: '\\babortion\\b' },
      { label: 'unborn', source: '\\bunborn\\b' },
      { label: 'fetal', source: '\\bfetal\\b|\\bfetus\\b' },
      { label: 'pregnancy_termination', source: '\\bpregnan(?:cy|t)[^.!?]{0,70}\\b(?:termination|abort)\\w*\\b' },
      { label: 'reproductive_policy', source: '\\breproductive (?:freedom|health|rights)\\b' },
    ],
  },
  {
    id: 'mathews_defund_planned_parenthood',
    sourceRows: [3, 12],
    memberName: 'Andrew Mathews',
    stance: 'supports',
    normalizedClaim: 'Andrew Mathews supports completely defunding Planned Parenthood in Minnesota.',
    issueFamily: 'planned_parenthood_funding',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'planned_parenthood', source: '\\bPlanned Parenthood\\b' },
    ],
  },
  {
    id: 'mathews_second_amendment',
    sourceRows: [4, 39],
    memberName: 'Andrew Mathews',
    stance: 'supports',
    normalizedClaim: 'Andrew Mathews supports Second Amendment rights.',
    issueFamily: 'second_amendment_gun_rights',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'second_amendment', source: '\\bSecond Amendment\\b|\\b2nd Amendment\\b' },
      { label: 'firearm', source: '\\bfirearms?\\b' },
      { label: 'gun_policy', source: '\\bgun(?:s| rights| control| registration)?\\b' },
      { label: 'background_check', source: '\\bbackground checks?\\b' },
      { label: 'red_flag', source: '\\bred flag\\b' },
    ],
  },
  {
    id: 'lang_pro_life',
    sourceRows: [8],
    memberName: 'Andrew R. Lang',
    stance: 'opposes',
    normalizedClaim: 'Andrew Lang opposes abortion and states a pro-life position.',
    issueFamily: 'abortion',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'abortion', source: '\\babortion\\b' },
      { label: 'unborn', source: '\\bunborn\\b' },
      { label: 'fetal', source: '\\bfetal\\b|\\bfetus\\b' },
      { label: 'reproductive_policy', source: '\\breproductive (?:freedom|health|rights)\\b' },
    ],
  },
  {
    id: 'murphy_minimum_wage_15_indexed',
    sourceRows: [9],
    memberName: 'Erin P. Murphy',
    stance: 'supports',
    normalizedClaim: 'Erin Murphy supports raising the minimum wage to $15 per hour indexed to inflation.',
    issueFamily: 'minimum_wage',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'minimum_wage', source: '\\bminimum wage\\b' },
      { label: 'hourly_wage', source: '\\bhourly wage\\b' },
      { label: 'fifteen_per_hour', source: '\\$?15(?:\\.00)?\\s*(?:per|/)\\s*(?:hour|hr)\\b' },
    ],
  },
  {
    id: 'jasinski_stand_your_ground',
    sourceRows: [10],
    memberName: 'John R. Jasinski',
    stance: 'supports',
    normalizedClaim: 'John Jasinski supports expanding Minnesota’s Stand Your Ground law.',
    issueFamily: 'stand_your_ground_self_defense',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'stand_your_ground', source: '\\bStand Your Ground\\b' },
      { label: 'duty_to_retreat', source: '\\bduty to retreat\\b' },
      { label: 'self_defense', source: '\\bself[- ]defen[cs]e\\b' },
      { label: 'use_of_force', source: '\\buse of force\\b' },
    ],
  },
  {
    id: 'coleman_parental_education_control',
    sourceRows: [13, 35],
    memberName: 'Julia E. Coleman',
    stance: 'supports',
    normalizedClaim: 'Julia Coleman supports putting more power in parents’ hands over their children’s education.',
    issueFamily: 'parental_education_control',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'school_choice', source: '\\bschool choice\\b' },
      { label: 'education_savings', source: '\\beducation savings (?:account|program)s?\\b' },
      { label: 'parental_rights', source: '\\bparent(?:al|s) rights?\\b' },
      { label: 'parent_notification', source: '\\bparent(?:al|s)[^.!?]{0,80}\\b(?:notice|notification|curriculum|instruction|education|school)\\b' },
      { label: 'private_school', source: '\\bprivate schools?\\b|\\bnon[- ]?public schools?\\b' },
    ],
  },
  {
    id: 'hoffman_close_corporate_tax_loopholes',
    sourceRows: [14],
    memberName: 'John A. Hoffman',
    stance: 'supports',
    normalizedClaim: 'John Hoffman supports closing corporate income-tax loopholes.',
    issueFamily: 'corporate_tax_loopholes',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'tax_loophole', source: '\\btax loopholes?\\b' },
      { label: 'corporate_income_tax', source: '\\bcorporate income tax\\b' },
      { label: 'corporate_tax', source: '\\bcorporate[^.!?]{0,60}\\btax\\b|\\btax[^.!?]{0,60}\\bcorporat(?:e|ion)\\b' },
    ],
  },
  {
    id: 'hoffman_hate_crime_penalty_enhancement',
    sourceRows: [17],
    memberName: 'John A. Hoffman',
    stance: 'supports',
    normalizedClaim: 'John Hoffman supports enhanced penalties for bias-motivated felony assault.',
    issueFamily: 'hate_crime_penalty_enhancement',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'hate_crime', source: '\\bhate crimes?\\b' },
      { label: 'bias_motivated', source: '\\bbias[- ]motivated\\b|\\bmotivated by bias\\b' },
      { label: 'bias_crime', source: '\\bbias crimes?\\b' },
      { label: 'penalty_bias', source: '\\bpenalt(?:y|ies)[^.!?]{0,100}\\bbias\\b|\\bbias[^.!?]{0,100}\\bpenalt(?:y|ies)\\b' },
    ],
  },
  {
    id: 'hoffman_gas_tax_opposition',
    sourceRows: [18],
    memberName: 'John A. Hoffman',
    stance: 'opposes',
    normalizedClaim: 'John Hoffman opposes gas-tax and vehicle-registration-fee increases.',
    issueFamily: 'gas_tax',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'gas_tax', source: '\\bgas(?:oline)? tax\\b' },
      { label: 'motor_fuel_tax', source: '\\bmotor fuel tax\\b' },
      { label: 'fuel_tax', source: '\\bfuel tax\\b' },
      { label: 'gasoline_tax_near', source: '\\b(?:tax|rate)[^.!?]{0,60}\\bgasoline\\b|\\bgasoline[^.!?]{0,60}\\b(?:tax|rate)\\b' },
      { label: 'registration_fee', source: '\\bregistration fee(?:s)?\\b|\\bvehicle registration\\b' },
    ],
  },
  {
    id: 'hoffman_solar_standard',
    sourceRows: [19],
    memberName: 'John A. Hoffman',
    stance: 'supports',
    normalizedClaim: 'John Hoffman supports a solar-energy standard and community solar.',
    issueFamily: 'solar_energy_standard',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'solar_standard', source: '\\bsolar standard\\b' },
      { label: 'community_solar', source: '\\bcommunity solar\\b' },
      { label: 'solar_energy', source: '\\bsolar (?:energy|power|generation|facility|facilities)\\b' },
      { label: 'renewable_standard', source: '\\brenewable (?:energy )?standard\\b' },
    ],
  },
  {
    id: 'utke_gas_tax_opposition',
    sourceRows: [21],
    memberName: 'Paul J. Utke',
    stance: 'opposes',
    normalizedClaim: 'Paul Utke opposes a gas-tax increase.',
    issueFamily: 'gas_tax',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'gas_tax', source: '\\bgas(?:oline)? tax\\b' },
      { label: 'motor_fuel_tax', source: '\\bmotor fuel tax\\b' },
      { label: 'fuel_tax', source: '\\bfuel tax\\b' },
      { label: 'gasoline_tax_near', source: '\\b(?:tax|rate)[^.!?]{0,60}\\bgasoline\\b|\\bgasoline[^.!?]{0,60}\\b(?:tax|rate)\\b' },
    ],
  },
  {
    id: 'utke_law_enforcement_resources',
    sourceRows: [22],
    memberName: 'Paul J. Utke',
    stance: 'supports',
    normalizedClaim: 'Paul Utke supports providing law enforcement with additional tools and resources.',
    issueFamily: 'law_enforcement_resources',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'law_enforcement', source: '\\blaw enforcement\\b' },
      { label: 'peace_officer', source: '\\bpeace officers?\\b' },
      { label: 'police_officer', source: '\\bpolice officers?\\b' },
      { label: 'police_department', source: '\\bpolice departments?\\b' },
    ],
  },
  {
    id: 'duckworth_parental_education_choice',
    sourceRows: [24],
    memberName: 'Zach Duckworth',
    stance: 'supports',
    normalizedClaim: 'Zach Duckworth supports parental choice in children’s education.',
    issueFamily: 'parental_education_choice',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'school_choice', source: '\\bschool choice\\b' },
      { label: 'education_savings', source: '\\beducation savings (?:account|program)s?\\b' },
      { label: 'parental_choice', source: '\\bparent(?:al|s)[^.!?]{0,80}\\bchoice\\b|\\bchoice[^.!?]{0,80}\\bparent(?:al|s)\\b' },
      { label: 'private_school', source: '\\bprivate schools?\\b|\\bnon[- ]?public schools?\\b' },
    ],
  },
  {
    id: 'koran_end_emergency_powers',
    sourceRows: [26],
    memberName: 'Mark W. Koran',
    stance: 'supports',
    normalizedClaim: 'Mark Koran supports ending Governor Walz’s emergency powers.',
    issueFamily: 'executive_emergency_powers',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'peacetime_emergency', source: '\\bpeacetime emergency\\b' },
      { label: 'emergency_powers', source: '\\bemergency powers?\\b' },
      { label: 'emergency_declaration', source: '\\bemergency declaration\\b' },
      { label: 'executive_order', source: '\\bexecutive orders?\\b' },
    ],
  },
  {
    id: 'koran_gas_tax_opposition',
    sourceRows: [30],
    memberName: 'Mark W. Koran',
    stance: 'opposes',
    normalizedClaim: 'Mark Koran opposes raising taxes, including a gas-tax increase, to fund transportation.',
    issueFamily: 'gas_tax',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'gas_tax', source: '\\bgas(?:oline)? tax\\b' },
      { label: 'motor_fuel_tax', source: '\\bmotor fuel tax\\b' },
      { label: 'fuel_tax', source: '\\bfuel tax\\b' },
      { label: 'gasoline_tax_near', source: '\\b(?:tax|rate)[^.!?]{0,60}\\bgasoline\\b|\\bgasoline[^.!?]{0,60}\\b(?:tax|rate)\\b' },
    ],
  },
  {
    id: 'hoffman_disability_employment_protections',
    sourceRows: [38],
    memberName: 'John A. Hoffman',
    stance: 'supports',
    normalizedClaim: 'John Hoffman supports stronger disability-employment protections and ADA compliance in state agencies.',
    issueFamily: 'disability_employment_protections',
    screenPolicy: 'screen_issue_match',
    candidatePatterns: [
      { label: 'ada', source: '\\bAmericans with Disabilities Act\\b|\\bADA\\b' },
      { label: 'disability_employment', source: '\\bdisabilit(?:y|ies)[^.!?]{0,100}\\bemployment\\b|\\bemployment[^.!?]{0,100}\\bdisabilit(?:y|ies)\\b' },
      { label: 'reasonable_accommodation', source: '\\breasonable accommodations?\\b' },
      { label: 'state_employment_disability', source: '\\bstate (?:agency|agencies|employment)[^.!?]{0,120}\\bdisabilit(?:y|ies)\\b|\\bdisabilit(?:y|ies)[^.!?]{0,120}\\bstate (?:agency|agencies|employment)\\b' },
    ],
  },
] as const;

export const P2_REMAINING_NOVEL_SEMANTIC_KEYS = Object.freeze(
  P2_REMAINING_APPLICABILITY_RULES.map((rule) => rule.id).sort(),
);
